const ACTIONS = {
  NARUTO_DATA_FETCH_INIT: 'NARUTO_DATA_FETCH_INIT',
  NARUTO_DATA_FETCH_SUCCESS: 'NARUTO_DATA_FETCH_SUCCESS',
  NARUTO_DATA_FETCH_FAIL: 'NARUTO_DATA_FETCH_FAIL',
  NARUTO_DATA_INVALIDATE: 'NARUTO_DATA_INVALIDATE'
};

export default ACTIONS;
